    
    //In real world this class is generated by tool
    public partial class TradingStrategy
    {
        public void InitializeStrategy()
        {}
    }

    //In real world this class is defined by traders
    public partial class TradingStrategy
    {
        public void CalculateRisk()
        {}
    }

    class PartialTypes
    {
        static void Main(string[] args)
        {
            TradingStrategy tradStrat = new TradingStrategy();
        }
    }
