//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace STPServiceConsumer.STPProvider {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PostTradeServiceSoap", Namespace="http://tempuri.org/")]
    public class PostTradeServiceWse : Microsoft.Web.Services2.WebServicesClientProtocol {
        
        /// <remarks/>
        public PostTradeServiceWse() {
            this.Url = "http://localhost/STPProvider/PostTradeService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubmitContractNote", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SubmitContractNote(ContractNoteInfo contractNote) {
            object[] results = this.Invoke("SubmitContractNote", new object[] {
                        contractNote});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSubmitContractNote(ContractNoteInfo contractNote, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SubmitContractNote", new object[] {
                        contractNote}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSubmitContractNote(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PostTradeServiceSoap", Namespace="http://tempuri.org/")]
    public class PostTradeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public PostTradeService() {
            this.Url = "http://localhost/STPProvider/PostTradeService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubmitContractNote", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SubmitContractNote(ContractNoteInfo contractNote) {
            object[] results = this.Invoke("SubmitContractNote", new object[] {
                        contractNote});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSubmitContractNote(ContractNoteInfo contractNote, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SubmitContractNote", new object[] {
                        contractNote}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSubmitContractNote(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class ContractNoteInfo {
        
        /// <remarks/>
        public string Symbol;
        
        /// <remarks/>
        public int Quantity;
        
        /// <remarks/>
        public System.Double Price;
        
        /// <remarks/>
        public BuySellEnum BuySell;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum BuySellEnum {
        
        /// <remarks/>
        Buy,
        
        /// <remarks/>
        Sell,
    }
}
